# Generated by Django 4.1.5 on 2023-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnerrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("i", "in"),
                    ("a", "absent"),
                    ("oh", "out (home)"),
                    ("ol", "out (lunch)"),
                    ("ov", "out (VAB)"),
                    ("oy", "out (YMCA)"),
                    ("oc", "out (Crag X)"),
                    ("oa", "out (appointment)"),
                    ("ox", "out (other)"),
                ],
                max_length=2,
            ),
        ),
    ]
