# Generated by Django 4.1.5 on 2023-01-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_learnerrecord_notes_alter_learnerrecord_action"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learner",
            old_name="surname",
            new_name="last_name",
        ),
        migrations.AlterField(
            model_name="learner",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
